version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:latest
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/iamolegga/enviper
    steps:
      - checkout
      - run:
          name: Install Reporter
          command: |
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter;
              chmod +x ./cc-test-reporter
            fi
      - run:
          name: Run Tests
          command: |
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              ./cc-test-reporter before-build
            fi
            make coverage
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              ./cc-test-reporter after-build -t gocov -p $(go list -m) --exit-code $?
            fi

workflows:
  version: 2
  workflow:
    jobs:
      - test
